name: Release A New Version

on:
    push:
        tags:
            - "*"

permissions:
    contents: write
    issues: write
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - uses: oven-sh/setup-bun@v1
              with:
                  bun-version: latest

            - run: bun install

            - run: bun run lint

            - run: bun run test

            - run: bun run build

            - run: bunx semantic-release
              if: startsWith(github.ref, 'refs/tags/')
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
